title: project-demo
description: describe project details
vars:
  version: 0.1.4
  chechpoint_dir: checkpoints
  temperature: 0.8
  repo_id: Qwen/Qwen1.5-7B-Chat
check_requirements: false
workflows:
  all: 
    - download
    - convert
commands:
      
  - name: build
    help: 重新打包并安装
    script:
      - poetry build
      - pip install dist/osc_llm-${vars.version}.tar.gz

  - name: download
    help: 下载原始模型,如果已经下载过则不会重复下载
    script:
      - llm download --repo_id ${vars.repo_id} --save_dir ${vars.chechpoint_dir}

  - name: convert
    help: 转换模型
    script:
      - llm convert ${vars.chechpoint_dir}/${vars.repo_id}

  - name: chat
    help: 与模型进行对话
    script:
      - llm chat --temperature ${vars.temperature} --checkpoint_dir ${vars.chechpoint_dir}/${vars.repo_id} --max_length 1024
