title: project-demo
description: describe project details
vars:
  version: 0.1.3
  chechpoint_dir: checkpoints
  temperature: 0.8
check_requirements: false
workflows:
  all: 
    - download
    - convert
    - chat
  test:
    - install 
    - chat
commands:
  - name: chat
    help: 与机器人聊天
    script:
      - llm chat ${vars.chechpoint_dir}/${vars.repo_id} --temperature ${vars.temperature} --accelerator cuda
      
  - name: install
    help: 重新打包并安装
    script:
      - poetry build
      - pip install dist/osc_llm-${vars.version}.tar.gz

  - name: download
    help: 下载原始模型,如果已经下载过则不会重复下载
    script:
      - llm download --repo_id ${vars.repo_id} --save_dir ${vars.chechpoint_dir}

  - name: convert
    help: 转换模型
    script:
      - llm convert ${vars.chechpoint_dir}/${vars.repo_id}
