[tool.poetry]
name = "osc-llm"
version = "0.1.0"
description = "复现主流中文大语言模型"
authors = ["wangmengdi <790990241@qq.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.8"
bitsandbytes = {version = ">=0.41.1", optional = true}
sentencepiece = ">=0.1.99"
tokenizers = ">=0.13.3"
huggingface_hub = ">=0.17.1"

[tool.poetry.extras]
quantize = ["bitsandbytes"]

[tool.poetry.scripts]
llm = "osc_llm.cli:app"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
